image: docker:latest

variables:
  REPOSITORY_URL: apprepo
  IMAGE_TAG: latest
  SERVICES_NAME: app-api

services:
- docker:dind

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - echo "Building image..."
    - docker build 
      -t $REPOSITORY_URL:$IMAGE_TAG
      --no-cache .
  only:
    - master

deploy:
  stage: deploy
  script:
    - docker stop $SERVICES_NAME || true && docker rm $SERVICES_NAME || true
    - docker container run -dt -v /data/app/uploads/:/home/node/app/uploads -p $PORT:$PORT --restart=always --env-file=.env --name $SERVICES_NAME $REPOSITORY_URL:$IMAGE_TAG
    - docker image prune -f
  only:
    - master